spring.application.name=curso-api

spring.datasource.url=jdbc:postgresql://localhost:5432/curso_api
spring.datasource.username=nadertaha
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update


